name: SampleImage
# configs:
#     Debug: debug
#     Release: release
# configFiles:
#   Debug: configs/Debug.xcconfig
#   Release: configs/Release.xcconfig
options:
  bundleIdPrefix: com.sakiyamaK
  deploymentTarget:
    iOS: 13.0
packages:
  IQKeyboardManagerSwift:
      url: https://github.com/hackiftekhar/IQKeyboardManager
      from: 6.5.0
  SnapKit:
      url: https://github.com/SnapKit/SnapKit
      from: 5.0.1
configs:
  Debug: debug
  Release: release
schemes:
  SampleImage:
    build:
      targets:
        SampleImage: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - SampleImage
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

targets:
  SampleImage:
    platform: iOS
    type: application
    dependencies:
      - package: IQKeyboardManagerSwift
      - package: SnapKit
    sources:
      - path: SampleImage/
    preBuildScripts:
        - path: /bin/sh
          name: Run Script(SwiftLint)
          script: |
            if which swiftlint >/dev/null; then
              swiftlint
            else
              echo "warning: Mintがインストールされていません。こちらからダウンロードしてください https://github.com/yonaskolb/Mint"
            fi
        - path: /bin/sh
          name: Run Script(R.swift)
          script: |
                "$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/R.generated.swift"
          inputFiles:
                - $TEMP_DIR/rswift-lastrun
          outputFiles:
                - $SRCROOT/R.generated.swift